[functions]

  # Flags "node-fetch" as an external node module for all functions.
  external_node_modules = ["node-fetch"]

  # Includes all wiki json files
  included_files = ["operas.json", "languages.json", "wiki/**", "utils/**"]

[dev]
  targetPort = 5173

[[redirects]]
  from = "/random"
  to = "/"
  status = 301
  force = false
  query = {random = "true"}

[[redirects]]
  from = "/wiki/*"
  to = "/"
  status = 301
  force = false
  query = {title = ":splat"}
